/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SchedulePackage;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author Jen
 */
public class EditMain extends javax.swing.JDialog {

    /**
     * Creates new form EditMain
     */
    public EditMain(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setSize(620, 510);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("NlexLogo1.png")));
        this.setTitle("Traffic Systems Engineering v.0.1");
        pleaseLbl.setVisible(true);

        for (int x = 0; x < VariableClass.equipmentList.size(); x++) {
            eLocation.addItem(VariableClass.equipmentList.get(x).toString());
            pleaseLbl.setVisible(false);

        }
        equipment.setSelectedItem(VariableClass.equipment.get(VariableClass.mainScreenSelected).toString());
        location.setSelectedItem(VariableClass.location.get(VariableClass.mainScreenSelected).toString());
        eLocation.setSelectedItem(VariableClass.equipmentLocation.get(VariableClass.mainScreenSelected).toString());
        dateLbl.setText("Date: " + VariableClass.sched.get(VariableClass.mainScreenSelected).toString());

        if (!VariableClass.type.get(VariableClass.mainScreenSelected).toString().equals("CM")
                || !VariableClass.type.get(VariableClass.mainScreenSelected).toString().equals("PM")) {
            if (VariableClass.type.get(VariableClass.mainScreenSelected).toString().equals("CM")) {
                jComboBox1.setSelectedIndex(0);
            } else {
                jComboBox1.setSelectedIndex(1);
            }
        } else {
            jComboBox1.setSelectedIndex(2);
            typeField.setText(VariableClass.type.get(VariableClass.mainScreenSelected).toString());
        }

        jComboBox2.setSelectedItem(VariableClass.status.get(VariableClass.mainScreenSelected).toString().trim());
        addTaskArea.setText(VariableClass.task.get(VariableClass.mainScreenSelected).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pane1 = new javax.swing.JScrollPane();
        addTaskArea = new javax.swing.JTextArea();
        typeField = new javax.swing.JTextField();
        birthLabel3 = new javax.swing.JLabel();
        typeTxt = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        birthLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        birthLabel7 = new javax.swing.JLabel();
        equipment = new javax.swing.JComboBox<>();
        birthLabel9 = new javax.swing.JLabel();
        eLocation = new javax.swing.JComboBox<>();
        birthLabel10 = new javax.swing.JLabel();
        pleaseLbl = new javax.swing.JLabel();
        typeTxt1 = new javax.swing.JLabel();
        typeField1 = new javax.swing.JTextField();
        location = new javax.swing.JComboBox<>();
        birthLabel8 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(405, 628));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(255, 204, 0));
        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLbl.setText("Date: Tuesday November 33, 3333");
        jPanel1.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 620, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Edit Task", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(255, 204, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addTaskArea.setColumns(20);
        addTaskArea.setLineWrap(true);
        addTaskArea.setRows(5);
        addTaskArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTaskAreaMouseClicked(evt);
            }
        });
        pane1.setViewportView(addTaskArea);

        jPanel3.add(pane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 400, 40));

        typeField.setEnabled(false);
        typeField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeFieldMouseClicked(evt);
            }
        });
        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });
        typeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                typeFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                typeFieldKeyReleased(evt);
            }
        });
        jPanel3.add(typeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 240, 40));

        birthLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        birthLabel3.setForeground(new java.awt.Color(255, 204, 0));
        birthLabel3.setText("Description:");
        jPanel3.add(birthLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, -1));

        typeTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        typeTxt.setForeground(new java.awt.Color(255, 204, 0));
        typeTxt.setText("Specify:");
        jPanel3.add(typeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 114, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CM", "PM", "Other" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, 40));

        birthLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        birthLabel6.setForeground(new java.awt.Color(255, 204, 0));
        birthLabel6.setText("Type:");
        jPanel3.add(birthLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 114, -1));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 60, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ongoing", "Complete" }));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 130, 40));

        birthLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        birthLabel7.setForeground(new java.awt.Color(255, 204, 0));
        birthLabel7.setText("Status:");
        jPanel3.add(birthLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 114, -1));

        equipment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equipment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Traffic & Tollplaza", "Tollbooth & Auxiliary", "ODS and VMS", "CS & AVLS", "Speed", "ECB", "Other" }));
        equipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equipmentMouseClicked(evt);
            }
        });
        equipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentActionPerformed(evt);
            }
        });
        jPanel3.add(equipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 130, 40));

        birthLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        birthLabel9.setForeground(new java.awt.Color(255, 204, 0));
        birthLabel9.setText("Equipment:");
        jPanel3.add(birthLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 114, -1));

        eLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eLocationMouseClicked(evt);
            }
        });
        eLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLocationActionPerformed(evt);
            }
        });
        jPanel3.add(eLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 40));

        birthLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        birthLabel10.setForeground(new java.awt.Color(255, 204, 0));
        birthLabel10.setText("Equipment Location:");
        jPanel3.add(birthLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, -1));

        pleaseLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pleaseLbl.setForeground(new java.awt.Color(255, 204, 0));
        pleaseLbl.setText("*Please add Location");
        jPanel3.add(pleaseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        typeTxt1.setBackground(new java.awt.Color(255, 204, 0));
        typeTxt1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        typeTxt1.setForeground(new java.awt.Color(255, 204, 0));
        typeTxt1.setText("Specify:");
        typeTxt1.setEnabled(false);
        jPanel3.add(typeTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        typeField1.setEnabled(false);
        typeField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeField1MouseClicked(evt);
            }
        });
        typeField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeField1ActionPerformed(evt);
            }
        });
        typeField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                typeField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                typeField1KeyReleased(evt);
            }
        });
        jPanel3.add(typeField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 190, 40));

        location.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NLEX", "SCTEX" }));
        jPanel3.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, 40));

        birthLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        birthLabel8.setForeground(new java.awt.Color(255, 204, 0));
        birthLabel8.setText("Location:");
        jPanel3.add(birthLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 114, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 600, 360));

        addBtn.setText("Update");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addTaskAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTaskAreaMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_addTaskAreaMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        try {

            // create a java mysql database connection
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/trafficsystems";
            Connection conn = DriverManager.getConnection(url, "root", "admin");

            // create the java mysql update preparedstatement
            String query = "update sched set equipment = ?,type = ?,status = ?,task = ?,location = ?, equipmentLocation=? where schedId = ?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);

            preparedStmt.setInt(7, VariableClass.schedId.get(VariableClass.mainScreenSelected));

            // execute the java preparedstatement
            if (jComboBox2.getSelectedIndex() == 6) {
                VariableClass.equipment.set(VariableClass.mainScreenSelected, typeField1.getText());
                preparedStmt.setString(1, typeField1.getText());
            } else {
                VariableClass.equipment.set(VariableClass.mainScreenSelected, equipment.getSelectedItem().toString());
                preparedStmt.setString(1, equipment.getSelectedItem().toString());
            }
            if (jComboBox1.getSelectedIndex() == 2) {
                VariableClass.type.set(VariableClass.mainScreenSelected, typeField.getText());
                preparedStmt.setString(2, typeField.getText());
            } else {
                VariableClass.type.set(VariableClass.mainScreenSelected, jComboBox1.getSelectedItem().toString());
                preparedStmt.setString(2, jComboBox1.getSelectedItem().toString());
            }
            VariableClass.status.set(VariableClass.mainScreenSelected, jComboBox2.getSelectedItem().toString());
            preparedStmt.setString(3, jComboBox2.getSelectedItem().toString());

            VariableClass.task.set(VariableClass.mainScreenSelected, addTaskArea.getText());
            preparedStmt.setString(4, addTaskArea.getText());

            VariableClass.location.set(VariableClass.mainScreenSelected, location.getSelectedItem().toString());
            preparedStmt.setString(5, location.getSelectedItem().toString());

            VariableClass.equipmentLocation.set(VariableClass.mainScreenSelected, eLocation.getSelectedItem().toString());
            preparedStmt.setString(6, eLocation.getSelectedItem().toString());

            preparedStmt.executeUpdate();
            conn.close();
            VariableClass.loadSched();
        } catch (Exception e) {
            System.out.println(e);
        }
        MainScreen.viewTaskRecords();
        dispose();

    }//GEN-LAST:event_addBtnActionPerformed

    private void typeFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeFieldMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldMouseClicked

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldActionPerformed

    private void typeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeFieldKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldKeyPressed

    private void typeFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeFieldKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldKeyReleased

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if (jComboBox1.getSelectedIndex() == 2) {
            typeField.setEnabled(true);
            typeTxt.setEnabled(true);
            typeField.setText("");
        } else {
            typeField.setEnabled(false);
            typeTxt.setEnabled(false);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// dateLbl.setText("Date: " + VariableClass.sched.get(VariableClass.mainScreenSelected).toString());
//        titleField.setText(VariableClass.title.get(VariableClass.mainScreenSelected).toString());
//        if (!VariableClass.type.get(VariableClass.mainScreenSelected).toString().equals("CM")
//                || !VariableClass.type.get(VariableClass.mainScreenSelected).toString().equals("PM")) {
//            if (VariableClass.type.get(VariableClass.mainScreenSelected).toString().equals("CM")) {
//                jComboBox1.setSelectedIndex(0);
//            } else {
//                jComboBox1.setSelectedIndex(1);
//            }
//        } else {
//            jComboBox1.setSelectedIndex(2);
//            typeField.setText(VariableClass.type.get(VariableClass.mainScreenSelected).toString());
//        }
//        addTaskArea.setText(VariableClass.task.get(VariableClass.mainScreenSelected).toString());

        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        typeField.setText("");
        addTaskArea.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void equipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equipmentMouseClicked
        if (equipment.getSelectedIndex() == 6) {
            typeField1.setEnabled(true);
            typeTxt1.setEnabled(true);
        } else {
            typeField1.setEnabled(false);
            typeTxt1.setEnabled(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentMouseClicked

    private void equipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentActionPerformed

    private void eLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eLocationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eLocationMouseClicked

    private void eLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eLocationActionPerformed

    private void typeField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_typeField1MouseClicked

    private void typeField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeField1ActionPerformed

    private void typeField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeField1KeyPressed

    private void typeField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typeField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_typeField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditMain dialog = new EditMain(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton addBtn;
    public static javax.swing.JTextArea addTaskArea;
    public static javax.swing.JLabel birthLabel10;
    public static javax.swing.JLabel birthLabel3;
    public static javax.swing.JLabel birthLabel6;
    public static javax.swing.JLabel birthLabel7;
    public static javax.swing.JLabel birthLabel8;
    public static javax.swing.JLabel birthLabel9;
    private javax.swing.JLabel dateLbl;
    public static javax.swing.JComboBox<String> eLocation;
    public static javax.swing.JComboBox<String> equipment;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JComboBox<String> location;
    public static javax.swing.JScrollPane pane1;
    public static javax.swing.JLabel pleaseLbl;
    public static javax.swing.JTextField typeField;
    public static javax.swing.JTextField typeField1;
    public static javax.swing.JLabel typeTxt;
    public static javax.swing.JLabel typeTxt1;
    // End of variables declaration//GEN-END:variables
}
