package SchedulePackage;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jen
 */
public class Register extends javax.swing.JFrame {

    public static void copyFile_Java7(String origin, String destination) throws IOException {
        Path FROM = Paths.get(origin);
        Path TO = Paths.get(destination);
        //overwrite the destination file if it exists, and copy
        // the file attributes, including the rwx permissions
        CopyOption[] options = new CopyOption[]{
            StandardCopyOption.REPLACE_EXISTING,
            StandardCopyOption.COPY_ATTRIBUTES
        };
        Files.copy(FROM, TO, options);
    }

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(imageLbl.getWidth(), imageLbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    public static String path = "";
    public static JFileChooser file1 = new JFileChooser();

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setResizable(false);
        this.setSize(465, 630);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("NlexLogo1.png")));
        this.setTitle("Traffic Systems Engineering v.0.1");

        bdayDateChooser.setSelectedDate(null);

        imageLbl.setIcon(ResizeImage("Img\\" + "noImgSelect" + ".png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        imageLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lnameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mnameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bdayDateChooser = new datechooser.beans.DateChooserCombo();
        repasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);

        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Choose Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile Picture", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));

        imageLbl.setBackground(new java.awt.Color(255, 255, 255));
        imageLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 65, 24));

        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, 35));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 65, 24));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Re-Enter Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 121, 24));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("First Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 93, 24));

        fnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(fnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 179, 35));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Last Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 65, 24));

        lnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(lnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 179, 35));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Middle Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 24));

        mnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(mnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 179, 35));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Birthday");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, 24));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 121, 24));

        emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 377, 35));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Contact Number (11 digit)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 205, 24));

        contactField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 377, 35));

        jButton2.setForeground(new java.awt.Color(0, 51, 255));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, -1, -1));

        bdayDateChooser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED,
            (java.awt.Color)null,
            (java.awt.Color)null,
            (java.awt.Color)null,
            (java.awt.Color)null));
    bdayDateChooser.setCalendarPreferredSize(new java.awt.Dimension(350, 280));
    bdayDateChooser.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
    bdayDateChooser.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 14));
    jPanel1.add(bdayDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 180, 35));

    repasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jPanel1.add(repasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, 40));

    passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 180, 40));

    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SchedulePackage/Untitled-2.png"))); // NOI18N
    jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 610));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();

        Login log = new Login();
        log.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username = usernameField.getText().trim();
        String password = passwordField.getText().trim();
        String repassword = repasswordField.getText().trim();
        String fname = fnameField.getText().trim().toLowerCase();
        String lname = lnameField.getText().trim().toLowerCase();
        String mname = mnameField.getText().trim().toLowerCase();
        String bday = bdayDateChooser.getText().toString().trim();
        String email = emailField.getText().trim();
        String contact = contactField.getText().trim();

        if (username.equals("") || password.equals("") || repassword.equals("") || fname.equals("") || lname.equals("")
                || mname.equals("") || bday.equals("") || email.equals("") || bday.equals("") || Pattern.matches("[a-zA-Z]+", contactField.getText().trim())
                || contactField.getText().trim().length() != 11) {
            if (username.equals("") || password.equals("") || repassword.equals("") || fname.equals("") || lname.equals("")
                    || mname.equals("") || bday.equals("") || email.equals("") || bday.equals("")) {
                JOptionPane.showMessageDialog(null, "Must Fill up all Required Fields", "Notice", JOptionPane.OK_OPTION);
            } else if (Pattern.matches("[a-zA-Z]+", contactField.getText().trim()) || contactField.getText().trim().length() != 11) {
                JOptionPane.showMessageDialog(null, "Number not valid", "Notice", JOptionPane.OK_OPTION);
            }

        } else {

//            dispose();
//            Login log = new Login();
//            log.setVisible(true);
            if (VariableClass.username.contains(username) || VariableClass.email.contains(email)
                    || VariableClass.contact.contains(contact) || !password.equals(repassword)) {
                if (VariableClass.username.contains(username)) {
                    JOptionPane.showMessageDialog(null, "Username already exist.", "Notice", JOptionPane.OK_OPTION);
                } else if (!password.equals(repassword)) {
                    JOptionPane.showMessageDialog(null, "Password do not match.", "Notice", JOptionPane.OK_OPTION);
                } else if (VariableClass.email.contains(email)) {
                    JOptionPane.showMessageDialog(null, "Email already exist.", "Notice", JOptionPane.OK_OPTION);
                } else if (VariableClass.contact.contains(contact)) {
                    JOptionPane.showMessageDialog(null, "Contact number already exist.", "Notice", JOptionPane.OK_OPTION);
                }

            } else {
                String firstname = fname.substring(0, 1).toUpperCase() + fname.substring(1).toLowerCase();
                String lastname = lname.substring(0, 1).toUpperCase() + lname.substring(1).toLowerCase();
                String middlename = mname.substring(0, 1).toUpperCase() + mname.substring(1).toLowerCase();
                String initials = "";
                for (int x = 0; x < firstname.length(); x++) {
                    if (x == 0) {
                        initials += firstname.substring(0, 1).toUpperCase();
                        firstname.substring(0, 1).toUpperCase();
                    } else if (firstname.charAt(x) == ' ') {
                        initials += firstname.substring(x + 1, x + 2).toUpperCase();
                        firstname.substring(x + 1, x + 2).toUpperCase();
                    }
                }
                for (int x = 0; x < middlename.length(); x++) {
                    if (x == 0) {
                        initials += mname.substring(0, 1).toUpperCase();
                        mname.substring(0, 1).toUpperCase();
                    } else if (middlename.charAt(x) == ' ') {
                        initials += middlename.substring(x + 1, x + 2).toUpperCase();
                        middlename.substring(x + 1, x + 2).toUpperCase();
                    }
                }
                for (int x = 0; x < lastname.length(); x++) {
                    if (x == 0) {
                        initials += lastname.substring(0, 1).toUpperCase();
                        lastname.substring(0, 1).toUpperCase();
                    } else if (lastname.charAt(x) == ' ') {
                        initials += lastname.substring(x + 1, x + 2).toUpperCase();
                        lastname.substring(x + 1, x + 2).toUpperCase();
                    }
                }
                VariableClass.initials.add(initials);
                VariableClass.username.add(username);
                VariableClass.password.add(password);
                VariableClass.fname.add(firstname);
                VariableClass.lname.add(lastname);
                VariableClass.mname.add(middlename);
                VariableClass.bday.add(bday);
                VariableClass.email.add(email);
                VariableClass.contact.add(contact);

                VariableClass.userStatus.add("Blocked");
                if (path.trim().equals("")) {
                    path = "Img\\" + "noImgSelect" + ".png";
                }
                String imgUser = "Img\\" + username + ".png";
                String imgUser1 = "dist\\Img\\" + username + ".png";
                try {
                    copyFile_Java7(path, imgUser);
                    copyFile_Java7(path, imgUser1);
                } catch (Exception e) {
                    System.out.println(e);
                }
                VariableClass.imgUser.add(imgUser);

                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    String url = "jdbc:mysql://localhost:3306/trafficsystems";
                    Connection conn = DriverManager.getConnection(url, "root", "admin");

                    Statement statement = conn.createStatement();
                    statement = conn.createStatement();
                    String sql = "INSERT INTO user (userId, initials,username,password,fname,lname,mname,bday,email,contact,userStatus,imgUser)"
                            + "VALUES (?, ? , ?, ? ,? , ? , ? , ? , ? , ? ,? , ?)";

                    PreparedStatement preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setInt(1, 0);
                    preparedStatement.setString(2, initials);
                    preparedStatement.setString(3, username);
                    preparedStatement.setString(4, password);
                    preparedStatement.setString(5, firstname);
                    preparedStatement.setString(6, lastname);
                    preparedStatement.setString(7, middlename);
                    preparedStatement.setString(8, bday);
                    preparedStatement.setString(9, email);
                    preparedStatement.setString(10, contact);
                    preparedStatement.setString(11, "Blocked");
                    preparedStatement.setString(12, imgUser);
                    preparedStatement.executeUpdate();
                    conn.close();
                } catch (Exception e) {
                    System.out.println("An error has occurred on Table Creation");
                    System.out.println(e);
                }

                VariableClass.loadUser();
                Login log = new Login();
                log.setVisible(true);
                dispose();
                System.out.println(imgUser);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        file.setPreferredSize(new Dimension(582, 382));
        int result = file.showSaveDialog(null);
        //if the user click on save in Jfilechooser
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            imageLbl.setIcon(ResizeImage(path));

        } //if the user click on save in Jfilechooser
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }        // TODO add your handling code here:
        file1 = file;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static datechooser.beans.DateChooserCombo bdayDateChooser;
    public static javax.swing.JTextField contactField;
    public static javax.swing.JTextField emailField;
    public static javax.swing.JTextField fnameField;
    private javax.swing.JLabel imageLbl;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JTextField lnameField;
    public static javax.swing.JTextField mnameField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField repasswordField;
    public static javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
