/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SchedulePackage;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jen
 */
public class UserList extends javax.swing.JDialog {

    public static void viewTaskRecords() {
        String col[] = new String[]{"Username", "Status"};
        DefaultTableModel model = new DefaultTableModel(col, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        Object rowData[] = new Object[2];
        for (int x = 1; x < VariableClass.username.size(); x++) {
            rowData[0] = VariableClass.username.get(x).toString();
            rowData[1] = VariableClass.userStatus.get(x).toString();
            model.addRow(rowData);
        }

        userTable.setModel(model);
        if (userTable.getRowCount() == 0) {
            jScrollPane1.setVisible(false);
            jButton1.setVisible(false);
            jLabel1.setVisible(true);
        } else {
            jScrollPane1.setVisible(true);
            jButton1.setVisible(true);
            jLabel1.setVisible(false);
        }

    }

    public UserList(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setSize(511,515);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("NlexLogo1.png")));
        this.setTitle("Traffic Systems Engineering v.0.1");
        viewTaskRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("NOTHING TO SHOW");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 400));

        jButton1.setText("Block/Unblock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, 30));

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, 30));

        jButton3.setText("Remove");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(VariableClass.userStatus.get(userTable.getSelectedRow()).toString());
        int select = userTable.getSelectedRow();
        select++;
        try {
            // create a java mysql database connection
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/trafficsystems";
            Connection conn = DriverManager.getConnection(url, "root", "admin");

            if (VariableClass.userStatus.get(select).toString().equals("Blocked")) {
                VariableClass.userStatus.set(select, "Unblocked");
                String query = "update user set userStatus = ? where userId = ?";
                PreparedStatement preparedStmt = conn.prepareStatement(query);
                preparedStmt.setString(1, "Unblocked");
                preparedStmt.setInt(2, VariableClass.userId.get(select));
                preparedStmt.executeUpdate();
                conn.close();
            } else {
                VariableClass.userStatus.set(select, "Blocked");
                String query = "update user set userStatus = ? where userId = ?";
                PreparedStatement preparedStmt = conn.prepareStatement(query);
                preparedStmt.setString(1, "Blocked");
                preparedStmt.setInt(2, VariableClass.userId.get(select));
                preparedStmt.executeUpdate();
                conn.close();
            }
            // create the java mysql update preparedstatement

        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        VariableClass.loadUser();
        viewTaskRecords();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int select = userTable.getSelectedRow() + 1;
        System.out.println(select);
        System.out.println(VariableClass.userId.get(select));
        try {
            // create a java mysql database connection
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/trafficsystems";
            Connection conn = DriverManager.getConnection(url, "root", "admin");

            String query = "delete from user where userId = ?";
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setInt(1, VariableClass.userId.get(select));
            preparedStmt.execute();
            conn.close();

            // create the java mysql update preparedstatement
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
        jButton3.setEnabled(false);

        VariableClass.userId.remove(userTable.getSelectedRow());
        VariableClass.username.remove(userTable.getSelectedRow());
        VariableClass.password.remove(userTable.getSelectedRow());
        VariableClass.fname.remove(userTable.getSelectedRow());
        VariableClass.lname.remove(userTable.getSelectedRow());
        VariableClass.mname.remove(userTable.getSelectedRow());
        VariableClass.bday.remove(userTable.getSelectedRow());
        VariableClass.email.remove(userTable.getSelectedRow());
        VariableClass.contact.remove(userTable.getSelectedRow());
        VariableClass.imgUser.remove(userTable.getSelectedRow());
        VariableClass.initials.remove(userTable.getSelectedRow());
        VariableClass.loadUser();
        viewTaskRecords();
// public static ArrayList userStatus = new ArrayList();
//    public static ArrayList username = new ArrayList();
//    public static ArrayList password = new ArrayList();
//    public static ArrayList fname = new ArrayList();
//    public static ArrayList lname = new ArrayList();
//    public static ArrayList mname = new ArrayList();
//    public static ArrayList bday = new ArrayList();
//    public static ArrayList email = new ArrayList();
//    public static ArrayList contact = new ArrayList();
//    public static ArrayList imgUser = new ArrayList();
//    public static ArrayList initials = new ArrayList();
//
//    public static ArrayList<Integer> userId = new ArrayList();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked

        jButton3.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_userTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserList dialog = new UserList(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
